name: Schedule Test

"on":
  schedule:
    - cron: "*/5 * * * *"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Print test message
        run: echo "Scheduled test ran successfully"
